export const theory: string[] = [
  '1. Phần biển báo',
  'a. Học thuộc những biển sau đây:',
  '<img:https://i.ibb.co/N76QKVM/meo-hoc-bien-bao.png>',
  'Chú ý:',
  'Biển cấm rẽ trái : Cấm cả quay đầu.',
  'Biển cấm quay đầu: Được rẽ trái.',
  'b. Các biển là đáp án đúng (nhìn thấy biển là khoanh luôn)',
  '<img:https://i.ibb.co/RD4H5Z5/bien-bao-stop-ah112ok.png>',
  '2. Phần lý thuyết',
  'a. Câu hỏi liên quan đến KHÁI NIỆM :',
  'Những câu hỏi về “khái niệm” hoặc “ hiểu như thế nào là đúng” thì có các từ trong ngoặc kép “…” ở đề bài thì để ý những từ sau:',
  '+ Vạch – Phố – Dải – Phần : Chọn đáp án (1). (Làn trong “Làn đường” , Tiên trong ” Đường ưu tiên” , Giới trong “Phương tiện giao thông cơ giới” )',
  '+ Khái niệm “ đường bộ”, “văn hóa giao thông” : Chọn đáp án (1) + (2).',
  '+ Khái niệm “Người điều khiển giao thông” : Chọn đáp án (2) + (3).',
  'b. Những câu luôn nằm trong ĐÁP ÁN ĐÚNG:',
  'Trong đáp án chứa những cụm từ sau , thì chọn luôn đáp án đó:',
  '+ Bị nghiêm cấm.',
  '+ Không được……. (không được phép, không được quay đầu).',
  '+ UBND cấp tỉnh.',
  '+ Cơ quan, tổ chức, cá nhân.',
  'c. Câu hỏi về NỒNG ĐỘ CỒN:',
  'Những câu hỏi về NỒNG ĐỘ CỒN, mà đề bài nhắc đến:',
  '+ Mô tô : thì chọn đáp án (1).',
  '+ Ô tô : thì chọn đáp án (2).',
  'd. Câu hỏi về HÀNH VI:',
  'Những câu hỏi về HÀNH VI mà:',
  '+ Có 2 đáp án: Chọn cả (1) và (2).',
  '+ Có 4 đáp án: Đọc hiểu.',
  'e. Câu hỏi về HIỆU LỆNH CSGT:',
  'Khi câu hỏi có nhắc đến HIỆU LỆNH của người điều khiển giao thông:',
  '+ Giơ: chọn đáp án (2).',
  '+ Giang: chọn đáp án (1).',
  'f. Câu hỏi về VÒNG XUYẾN :',
  '+ Có báo hiệu đi theo vòng xuyến >>nhường bên tay TRÁI',
  '+ Không có báo hiệu đi theo vòng xuyến >> nhường bên tay PHẢI',
  'g. Câu hỏi về ĐƯỜNG CAO TỐC:',
  '+ Vào đường cao tốc : Chọn đáp án (1) + (3).',
  '+ Ra đường cao tốc : Chọn đáp án (1).',
  'h. Câu hỏi về ĐÔNG DÂN CƯ:',
  '+  Đề bài không có số: chọn đáp án (2)',
  '+ Đề bài có số: chọn đáp án có từ “xe gắn máy” ở cuối đáp án.',
  'i. + Đề bài có số: chọn đáp án có từ “xe gắn máy” ở cuối đáp án.',
  'Những câu hỏi liên quan đến LÀN ĐƯỜNG, ta sẽ dựa vào độ dài đáp án:',
  '+ 3 đáp án có độ dài ngang nhau : chọn đáp án (2).',
  '+ 2 đáp án dài, 1 đáp án ngắn: chọn 2 đáp án dài.',
  'k. Câu hỏi liên quan đến CON SỐ:',
  'Các đáp án đúng: 5m, 5 năm, 18 tuổi, 40km/h, nhỏ hơn 70km/h.',
  '3. Phần sa hình',
  'a. Thứ tự đi phần sa hình:',
  '+ Thứ 1: Xe nào vào nơi giao nhau đi trước.',
  '+ Thứ 2: Xe ưu tiên đi trước: Quân sự, công an, cứu thương…',
  '+ Thứ 3: Xe nào đi trên đường ưu tiên thì được đi trước.',
  '+ Thứ 4: Xe bên phải không vướng đi trước.',
  '+ Thứ 5: Rẽ phải – Đi thẳng – Rẽ trái.',
  'b. XE CON LUÔN ĐÚNG: tức là xe con là từ khóa, xe con luôn chấp hành đúng quy tắc giao thông.',
  '+ Khi đề bài hỏi xe nào được quyền đi trước, xe nào chấp hành đúng luật giao thông =>>> Chọn đáp án có xe con.',
  '+ Khi đề bài hỏi xe nào vi phạm quy tắc giao thông =>> Chọn đáp án không có xe con (Vì xe con luôn đúng).',
  'c. Có hình CSGT hoặc VÒNG TRÒN hoặc VÒNG XUYẾN: Chọn đáp án số 3.',
  'Trong phần sa hình, câu nào xuất hiện hình CSGT hoặc VÒNG TRÒN, hoặc VÒNG XUYẾN thì chọn luôn đáp án số 3.',
  'd. ĐẾM SỐ XE : Trong phần sa hình , trong hình chỉ có mỗi xe không, không có biển , không có đèn gì cả, thì ĐẾM SỐ XE CHỌN ĐÁP ÁN: Có 3 xe chọn đáp án 3, 4 xe chọn đáp án 4.',
  'e. Có mũi tên màu đỏ: đếm ngã – 1 =>> ra đáp án',
  'Có 3 ngã thì đáp án 2, có 4 ngã thì đáp án 3.',
  'f. Có chữ Xe con (E) và “Xe xích lô” : chọn đáp án đúng luôn.'
]

export const pratice: string[] = [
  'a. Chạy theo vòng số 8',
  'Trong phần thi này thí sinh nên để số 2 đi luôn cho đầm máy. Khi chạy sa hình số 8, thí sinh nên hạ nhẹ ga xuống, Tuy nhiên tốc độ không nên quá chậm, nếu chạy nhanh có thể rà thắng từ từ để phần bánh trước của xe bám vào vành ngoài của vòng số 8. Đây là phần thi khó nhất của bài thực hành thi sát hạch lái xe mô tô và giám khảo cũng thường quan sát kỹ phần thi này nên các bạn cần lưu ý.',
  'b. Đi vào đường hẹp',
  'Trong phần thi này đường khá hẹp nên các bạn cần lưu ý chỉ nên đi với tốc độ vừa phải, và đi giữa đường để tránh bị chạm vạch.',
  'c. Chạy đường quanh co',
  'Trong ba phần của bài thi thực hành thi sát hạch lái xe mô tô, thí sinh nên nhảy ga đều đặn để xe ga nhịp nhàng. Phần thi ày đòi hỏi học viên cần có kỹ thuật đi vòng cua.',
  'd. Chạy đường gồ ghề',
  'Đây là phần thi thực hành cuối cùng. Các thí sinh phải giữ vững tay lái của mình tránh tình trangh mất lái, không nên đi với tốc độ quá chậm vì sẽ dễ ngã xe ảnh hưởng đến bài thi.'
]
